### ISSUE TITLE
slave build app docker image using dockerfile can not find app jar，the path is wrong

### ISSUE THREAD

**Issue by leiyazhen** [jenkinsci/docker-inbound-agent#95] opened 2019-09-04 09:07 UTC
jenkins system log is below：
```
/home/jenkins/agent/workspace/netplan-newradio/lcloud-netplan-eureka
[Pipeline] sh
+ docker build -f ./Dockerfile -t bd01:441/netplan-newradio/lcloud-netplan-eureka:head target/docker/
Sending build context to Docker daemon  1.583kB

Step 1/7 : FROM anapsix/alpine-java:8_server-jre_unlimited
 ---> 49d744fbb526
Step 2/7 : MAINTAINER leiyz@ling-cloud.com
 ---> Using cache
 ---> d858e661415b
Step 3/7 : RUN mkdir -p /home/program/lcloud-netplan-euraka
 ---> Using cache
 ---> 30a3cfdf54e4
Step 4/7 : WORKDIR /home/program/lcloud-netplan-euraka
 ---> Using cache
 ---> 78d1b449a716
Step 5/7 : EXPOSE 1025
 ---> Using cache
 ---> 0994455fcaae
Step 6/7 : ADD target/lcloud-netplan-euraka.jar ./
ADD failed: stat /data/k8s/docker/data/tmp/docker-builder074430824/target/lcloud-netplan-euraka.jar: no such file or directory
```
i am using maven to build app jar in target dir,and in my Dockerfile i use ADD target/lcloud-netplan-euraka.jar ./ to add app.jar，but actually the path turns to be /data/k8s/docker/data/tmp/docker-builder074430824/target/lcloud-netplan-euraka.jar.
however,/data/k8s/docker/data/tmp/ is the docker data dir on k8s host,i can not found any method to this,anyone can help me?

**Comment by dduportal** [comment] 2023-09-08 17:46
This is likely to be a pipeline + Docker problem. You might want to ask for help in the [community forums](https://community.jenkins.io).

Closing as it is not a bug in the image.

**Closed by dduportal** 2023-09-08 17:46 UTC
