### ISSUE TITLE
 ./gradlew: Permission denied

### ISSUE THREAD

**Issue by zhengjy** [jenkinsci/docker-inbound-agent#220] opened 2021-02-05 02:52 UTC
![image](https://user-images.githubusercontent.com/12868597/106983018-2f3eb880-67a0-11eb-8dfe-c3064d696894.png)
why?

**Comment by MarkEWaite** [comment] 2021-02-05 03:09
Probably don't have the execute permission bit set on the gradlew file in
the git repository.  Use `chmod 755 gradlew` to make it executable.

**Comment by H1rkul2** [comment] 2021-03-21 13:12
have tried making it executable  by executing  chmod +x gradlew ?

**Comment by dduportal** [comment] 2022-11-29 10:15
Closing as the issue is unrelated to the docker image (and a working solution is provided).

**Closed by dduportal** 2022-11-29 10:15 UTC
