### ISSUE TITLE
jnlp is unable to connect to master on latest windows release (May 12th)

### ISSUE THREAD

**Issue by dionjansen** [jenkinsci/docker-inbound-agent#174] opened 2020-05-26 07:57 UTC
When running the `docker-inbound-agent` using the [jenkins-kubernetes-plugin](https://github.com/jenkinsci/kubernetes-plugin) on nodes using the latest windows release `10.0.17763.1217` (May 12th release) it is unable to start because the master is not accessible to the agent. The agent is started in the same namespace as the master.

I am using: `jenkins/inbound-agent:jdk11-windowsservercore-1809`

Reverting my windows nodes back to the `10.0.17763.1158` (April 14th) release resolves the issue.

```log
2020-05-26 07:16:08.995+0000 [id=32]	INFO	o.c.j.p.k.KubernetesCloud#provision: Template for label Pipeline_tests_122-rp5c9: Pipeline_tests_122-rp5c9-ww2zb
2020-05-26 07:16:08.998+0000 [id=32]	INFO	o.c.j.p.k.KubernetesClientProvider#createClient: Created new Kubernetes client: kubernetes io.fabric8.kubernetes.client.DefaultKubernetesClient@25f45c6a
2020-05-26 07:16:09.047+0000 [id=32]	INFO	o.internal.platform.Platform#log: ALPN callback dropped: HTTP/2 is disabled. Is alpn-boot on the boot class path?
2020-05-26 07:16:19.004+0000 [id=33]	INFO	hudson.slaves.NodeProvisioner#lambda$update$6: pipeline-tests-122-rp5c9-ww2zb-600lx provisioning successfully completed. We have now 2 computer(s)
2020-05-26 07:16:19.031+0000 [id=3103]	INFO	o.c.j.p.k.KubernetesLauncher#launch: Created Pod: cicd/pipeline-tests-122-rp5c9-ww2zb-600lx
2020-05-26 07:16:19.083+0000 [id=3110]	INFO	o.internal.platform.Platform#log: ALPN callback dropped: HTTP/2 is disabled. Is alpn-boot on the boot class path?
2020-05-26 07:16:19.139+0000 [id=3111]	INFO	o.internal.platform.Platform#log: ALPN callback dropped: HTTP/2 is disabled. Is alpn-boot on the boot class path?
2020-05-26 07:17:10.538+0000 [id=3103]	INFO	o.c.j.p.k.KubernetesLauncher#launch: Pod is running: cicd/pipeline-tests-122-rp5c9-ww2zb-600lx
2020-05-26 07:17:10.545+0000 [id=3103]	INFO	o.c.j.p.k.KubernetesLauncher#launch: Waiting for agent to connect (0/100): pipeline-tests-122-rp5c9-ww2zb-600lx
2020-05-26 07:17:11.550+0000 [id=3103]	INFO	o.c.j.p.k.KubernetesLauncher#launch: Waiting for agent to connect (1/100): pipeline-tests-122-rp5c9-ww2zb-600lx
2020-05-26 07:17:12.555+0000 [id=3103]	INFO	o.c.j.p.k.KubernetesLauncher#launch: Waiting for agent to connect (2/100): pipeline-tests-122-rp5c9-ww2zb-600lx
2020-05-26 07:17:13.560+0000 [id=3103]	INFO	o.c.j.p.k.KubernetesLauncher#launch: Waiting for agent to connect (3/100): pipeline-tests-122-rp5c9-ww2zb-600lx
2020-05-26 07:17:14.566+0000 [id=3103]	INFO	o.c.j.p.k.KubernetesLauncher#launch: Waiting for agent to connect (4/100): pipeline-tests-122-rp5c9-ww2zb-600lx
2020-05-26 07:17:15.571+0000 [id=3103]	INFO	o.c.j.p.k.KubernetesLauncher#launch: Waiting for agent to connect (5/100): pipeline-tests-122-rp5c9-ww2zb-600lx
2020-05-26 07:17:16.577+0000 [id=3103]	INFO	o.c.j.p.k.KubernetesLauncher#launch: Waiting for agent to connect (6/100): pipeline-tests-122-rp5c9-ww2zb-600lx
2020-05-26 07:17:17.584+0000 [id=3103]	INFO	o.c.j.p.k.KubernetesLauncher#launch: Waiting for agent to connect (7/100): pipeline-tests-122-rp5c9-ww2zb-600lx
2020-05-26 07:17:18.594+0000 [id=3103]	INFO	o.c.j.p.k.KubernetesLauncher#launch: Waiting for agent to connect (8/100): pipeline-tests-122-rp5c9-ww2zb-600lx
2020-05-26 07:17:19.600+0000 [id=3103]	INFO	o.c.j.p.k.KubernetesLauncher#launch: Waiting for agent to connect (9/100): pipeline-tests-122-rp5c9-ww2zb-600lx
2020-05-26 07:17:20.605+0000 [id=3103]	INFO	o.c.j.p.k.KubernetesLauncher#launch: Waiting for agent to connect (10/100): pipeline-tests-122-rp5c9-ww2zb-600lx
2020-05-26 07:17:21.610+0000 [id=3103]	INFO	o.c.j.p.k.KubernetesLauncher#launch: Waiting for agent to connect (11/100): pipeline-tests-122-rp5c9-ww2zb-600lx
2020-05-26 07:17:22.616+0000 [id=3103]	INFO	o.c.j.p.k.KubernetesLauncher#launch: Waiting for agent to connect (12/100): pipeline-tests-122-rp5c9-ww2zb-600lx
2020-05-26 07:17:23.621+0000 [id=3103]	INFO	o.c.j.p.k.KubernetesLauncher#launch: Waiting for agent to connect (13/100): pipeline-tests-122-rp5c9-ww2zb-600lx
2020-05-26 07:17:24.629+0000 [id=3103]	INFO	o.c.j.p.k.KubernetesLauncher#launch: Waiting for agent to connect (14/100): pipeline-tests-122-rp5c9-ww2zb-600lx
2020-05-26 07:17:25.635+0000 [id=3103]	INFO	o.c.j.p.k.KubernetesLauncher#launch: Waiting for agent to connect (15/100): pipeline-tests-122-rp5c9-ww2zb-600lx
2020-05-26 07:17:26.640+0000 [id=3103]	INFO	o.c.j.p.k.KubernetesLauncher#launch: Waiting for agent to connect (16/100): pipeline-tests-122-rp5c9-ww2zb-600lx
2020-05-26 07:17:27.646+0000 [id=3103]	INFO	o.c.j.p.k.KubernetesLauncher#launch: Waiting for agent to connect (17/100): pipeline-tests-122-rp5c9-ww2zb-600lx
2020-05-26 07:17:28.684+0000 [id=3103]	SEVERE	o.c.j.p.k.KubernetesLauncher#logLastLines: Error in provisioning; agent=KubernetesSlave name: pipeline-tests-122-rp5c9-ww2zb-600lx, template=PodTemplate{, name='Pipeline_tests_122-rp5c9-ww2zb', namespace='cicd', label='Pipeline_tests_122-rp5c9', nodeUsageMode=EXCLUSIVE, workspaceVolume=EmptyDirWorkspaceVolume [memory=false], annotations=[org.csanchez.jenkins.plugins.kubernetes.PodAnnotation@aab9c821, org.csanchez.jenkins.plugins.kubernetes.PodAnnotation@c92c82e4]}. Container jnlp. Logs: May 26, 2020 7:17:12 AM org.jenkinsci.remoting.engine.WorkDirManager initializeWorkDir
INFO: Using \home\jenkins\agent\remoting as a remoting work directory
May 26, 2020 7:17:12 AM org.jenkinsci.remoting.engine.WorkDirManager setupLogging
INFO: Both error and output logs will be printed to \home\jenkins\agent\remoting
May 26, 2020 7:17:12 AM hudson.remoting.jnlp.Main$CuiListener status
INFO: Locating server among [http://jenkins-master:8080/]
May 26, 2020 7:17:25 AM hudson.remoting.jnlp.Main$CuiListener error
SEVERE: Failed to connect to http://jenkins-master:8080/tcpSlaveAgentListener/: jenkins-master
java.io.IOException: Failed to connect to http://jenkins-master:8080/tcpSlaveAgentListener/: jenkins-master
	at org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver.resolve(JnlpAgentEndpointResolver.java:217)
	at hudson.remoting.Engine.innerRun(Engine.java:693)
	at hudson.remoting.Engine.run(Engine.java:518)
Caused by: java.net.UnknownHostException: jenkins-master
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:607)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
	at sun.net.www.http.HttpClient.New(HttpClient.java:339)
	at sun.net.www.http.HttpClient.New(HttpClient.java:357)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1226)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:990)
	at org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver.resolve(JnlpAgentEndpointResolver.java:214)
	... 2 more


2020-05-26 07:17:28.684+0000 [id=3103]	WARNING	o.c.j.p.k.KubernetesLauncher#launch: Error in provisioning; agent=KubernetesSlave name: pipeline-tests-122-rp5c9-ww2zb-600lx, template=PodTemplate{, name='Pipeline_tests_122-rp5c9-ww2zb', namespace='cicd', label='Pipeline_tests_122-rp5c9', nodeUsageMode=EXCLUSIVE, workspaceVolume=EmptyDirWorkspaceVolume [memory=false], annotations=[org.csanchez.jenkins.plugins.kubernetes.PodAnnotation@aab9c821, org.csanchez.jenkins.plugins.kubernetes.PodAnnotation@c92c82e4]}
java.lang.IllegalStateException: Agent is not connected after 18 seconds, status: Succeeded
	at org.csanchez.jenkins.plugins.kubernetes.KubernetesLauncher.launch(KubernetesLauncher.java:208)
	at hudson.slaves.SlaveComputer.lambda$_connect$0(SlaveComputer.java:292)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:71)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2020-05-26 07:17:28.684+0000 [id=3103]	INFO	o.c.j.p.k.KubernetesSlave#_terminate: Terminating Kubernetes instance for agent pipeline-tests-122-rp5c9-ww2zb-600lx
Terminated Kubernetes instance for agent cicd/pipeline-tests-122-rp5c9-ww2zb-600lx
Disconnected computer pipeline-tests-122-rp5c9-ww2zb-600lx
2020-05-26 07:17:28.706+0000 [id=3103]	INFO	o.c.j.p.k.KubernetesSlave#deleteSlavePod: Terminated Kubernetes instance for agent cicd/pipeline-tests-122-rp5c9-ww2zb-600lx
2020-05-26 07:17:28.706+0000 [id=3103]	INFO	o.c.j.p.k.KubernetesSlave#_terminate: Disconnected computer pipeline-tests-122-rp5c9-ww2zb-600lx
2020-05-26 07:17:28.995+0000 [id=40]	INFO	o.c.j.p.k.KubernetesCloud#provision: Excess workload after pending Kubernetes agents: 1
```

**Comment by dionjansen** [comment] 2020-05-26 09:10
Initially I though this had something to do with `windowsservercore` version being outdated/ mismatched, so I  created my own `agent` and `inbound-agent` from scratch using the latest `adoptopenjdk:11-jdk-hotspot-windowsservercore-1809` but it still won't connect.

**Comment by rkivisto** [comment] 2020-08-04 18:00
It may be useful to go to `Manage Jenkins` -> `Configure System` and set your `Jenkins URL` to a fully qualified hostname, as the error appears to be an issue trying to look up `jenkins-master` and that fails to resolve:

```
java.net.UnknownHostException: jenkins-master
```

**Comment by drimailorr** [comment] 2020-09-01 13:07
The issue still persists. Jenkins master is resolvable within the pod.

**Comment by kapoorsunny** [comment] 2021-01-08 11:10
This issue still persists

**Comment by qalinn** [comment] 2021-05-04 08:18
The issue is still present. Do you have any workaround till will be fixed?

**Comment by rranjith406** [comment] 2021-05-28 09:04
I'm facing something similar error. I've my Jenkins master and agent running on K8s pod. 

![Capture1](https://user-images.githubusercontent.com/52668325/119958682-e31eba80-bfc0-11eb-96a5-5530fc476931.PNG)
Agent log 
![Capture2](https://user-images.githubusercontent.com/52668325/119959227-6dffb500-bfc1-11eb-902c-a176f22554b9.PNG)




This is my Master log

`2021-05-28 08:59:04.807+0000 [id=37]    INFO    hudson.slaves.NodeProvisioner#lambda$update$6: jenkins-slave-7w7lp provisioning successfully completed. We have now 2 computer(s)
2021-05-28 08:59:04.938+0000 [id=2793]  INFO    o.c.j.p.k.KubernetesLauncher#launch: Created Pod: kubernetes infra/jenkins-slave-7w7lp
2021-05-28 08:59:09.399+0000 [id=4211]  INFO    j.b.MultiBranchProject$BranchIndexing#run: TMOS Pipeline BE #20210528.085900 branch indexing action completed: SUCCESS in 8.5 sec
2021-05-28 08:59:16.024+0000 [id=2793]  INFO    o.c.j.p.k.KubernetesLauncher#launch: Pod is running: kubernetes infra/jenkins-slave-7w7lp
2021-05-28 08:59:46.248+0000 [id=2793]  INFO    o.c.j.p.k.KubernetesLauncher#launch: Waiting for agent to connect (30/100): jenkins-slave-7w7lp
2021-05-28 09:00:16.578+0000 [id=2793]  INFO    o.c.j.p.k.KubernetesLauncher#launch: Waiting for agent to connect (60/100): jenkins-slave-7w7lp
2021-05-28 09:00:46.782+0000 [id=2793]  INFO    o.c.j.p.k.KubernetesLauncher#launch: Waiting for agent to connect (90/100): jenkins-slave-7w7lp
2021-05-28 09:00:56.898+0000 [id=2793]  SEVERE  o.c.j.p.k.KubernetesLauncher#logLastLines: Error in provisioning; agent=KubernetesSlave name: jenkins-slave-7w7lp, template=PodTemplate{id='220600f0-4c60-4eec-9f80-a871414cfc2e', name='jenkins-slave', namespace='infra', nodeSelector='intent=apps,lifecycle=Ec2Spot', nodeUsageMode=NORMAL, volumes=[org.csanchez.jenkins.plugins.kubernetes.volumes.PersistentVolumeClaim@74f6bd9d, SecretVolume [mountPath=/mnt/keys, secretName=tmos-cert, defaultMode=256, optional=false]], containers=[ContainerTemplate{name='jnlp', image='805310764246.dkr.ecr.eu-central-1.amazonaws.com/jenkins-agent:v.1', privileged=true, alwaysPullImage=true, workingDir='/home/jenkins/agent', command='', args='', ttyEnabled=true, resourceRequestCpu='', resourceRequestMemory='', resourceRequestEphemeralStorage='', resourceLimitCpu='3000m', resourceLimitMemory='6000Mi', resourceLimitEphemeralStorage='', livenessProbe=ContainerLivenessProbe{execArgs='', timeoutSeconds=0, initialDelaySeconds=0, failureThreshold=0, periodSeconds=0, successThreshold=0}}]}. Container jnlp. Logs: about to fork child process, waiting until server is ready for connections.
forked process: 11
child process started successfully, parent exiting
fill mongo db ...
add git key for authenticatoin and user informations ...
mkdir: cannot create directory '/root/.ssh': File exists

2021-05-28 09:00:56.899+0000 [id=2793]  WARNING o.c.j.p.k.KubernetesLauncher#launch: Error in provisioning; agent=KubernetesSlave name: jenkins-slave-7w7lp, template=PodTemplate{id='220600f0-4c60-4eec-9f80-a871414cfc2e', name='jenkins-slave', namespace='infra', nodeSelector='intent=apps,lifecycle=Ec2Spot', nodeUsageMode=NORMAL, volumes=[org.csanchez.jenkins.plugins.kubernetes.volumes.PersistentVolumeClaim@74f6bd9d, SecretVolume [mountPath=/mnt/keys, secretName=tmos-cert, defaultMode=256, optional=false]], containers=[ContainerTemplate{name='jnlp', image='805310764246.dkr.ecr.eu-central-1.amazonaws.com/jenkins-agent:v.1', privileged=true, alwaysPullImage=true, workingDir='/home/jenkins/agent', command='', args='', ttyEnabled=true, resourceRequestCpu='', resourceRequestMemory='', resourceRequestEphemeralStorage='', resourceLimitCpu='3000m', resourceLimitMemory='6000Mi', resourceLimitEphemeralStorage='', livenessProbe=ContainerLivenessProbe{execArgs='', timeoutSeconds=0, initialDelaySeconds=0, failureThreshold=0, periodSeconds=0, successThreshold=0}}]}
java.lang.IllegalStateException: Agent is not connected after 100 seconds, status: Running
        at org.csanchez.jenkins.plugins.kubernetes.KubernetesLauncher.launch(KubernetesLauncher.java:244)
        at hudson.slaves.SlaveComputer.lambda$_connect$0(SlaveComputer.java:294)
        at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
        at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:71)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2021-05-28 09:00:56.899+0000 [id=2793]  INFO    o.c.j.p.k.KubernetesSlave#_terminate: Terminating Kubernetes instance for agent jenkins-slave-7w7lp
2021-05-28 09:00:56.989+0000 [id=2793]  INFO    o.c.j.p.k.KubernetesSlave#deleteSlavePod: Terminated Kubernetes instance for agent infra/jenkins-slave-7w7lp
Terminated Kubernetes instance for agent infra/jenkins-slave-7w7lp
2021-05-28 09:00:56.990+0000 [id=2793]  INFO    o.c.j.p.k.KubernetesSlave#_terminate: Disconnected computer jenkins-slave-7w7lp
Disconnected computer jenkins-slave-7w7lp
`

**Comment by gfrid** [comment] 2022-04-18 18:50
> The issue is still present. Do you have any workaround till will be fixed?

indeed just opened a new bug:
[https://github.com/jenkinsci/docker-inbound-agent/issues/266](url)

**Comment by dduportal** [comment] 2023-09-08 17:37
Closing as duplicate of https://github.com/jenkinsci/docker-inbound-agent/issues/266

**Closed by dduportal** 2023-09-08 17:37 UTC
